### ISSUE TITLE
கணியம் அறக்கட்டளை - பதிவு செய்க

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Organization#1]

**Comment by ssurenr** [comment]
மிக அருமை. வாழ்த்துக்கள்.

**Comment by tshrinivasan** [comment]
இன்று வழக்கறிஞர் சங்கர் அவர்களை சந்தித்தேன். அறக்கட்டளை உறுப்பினர்களின் பெயர், முகவரி, அடையாள அட்டை நகல்களைத்  தந்தேன்.

வரும் வெள்ளி இரவு வரச்சொன்னார்.

அடுத்த வாரம் பதிவு செய்ய, பதிவுத்துறை இணையதளத்தில் முன்பதிவு செய்து விடுவார்.

**Comment by tshrinivasan** [comment]
நீண்ட தொடர் முயற்சிகளுக்குப்பின், இன்று கணியம் அறக்கட்டளை பதிவு நடைபெற்றது.
http://www.kaniyam.com/kaniyam-foundation-international-day-against-drm/
