### ISSUE TITLE
இலச்சினை, சின்னம் உருவாக்குக (லோகோ)

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Organization#3]

**Comment by tshrinivasan** [comment]
![kaniyam-foundation](https://user-images.githubusercontent.com/1268536/39251218-62d9126e-48c0-11e8-870e-320ca367bf45.jpg)
![logo-3](https://user-images.githubusercontent.com/1268536/39251219-631f38e8-48c0-11e8-86f9-43e6eff9f0cd.png)
![logo-2](https://user-images.githubusercontent.com/1268536/39251221-6365c15a-48c0-11e8-8503-710ac234b717.jpg)
![kaniyam-logo](https://user-images.githubusercontent.com/1268536/39251222-63995d44-48c0-11e8-8324-f0584471415e.jpg)

**Comment by tshrinivasan** [comment]
used just TAU_Elango_Krishna font

**Comment by gurulenin** [comment]
![kaniyam](https://user-images.githubusercontent.com/15311390/40191103-20a25724-5a1e-11e8-8173-8e07ecf6ef57.png)

**Comment by gurulenin** [comment]
some ideas

**Comment by tshrinivasan** [comment]
Thanks for the great works.

Is it possible to add CC (creative commons) in the logo?



வியா., 17 மே, 2018, பிற்பகல் 10:04க்கு, gurulenin <notifications@github.com>
எழுதியது:

**Comment by gurulenin** [comment]
![kaniyam](https://user-images.githubusercontent.com/15311390/40237550-69144eee-5ace-11e8-8ef0-273e27de012c.png)

**Comment by gurulenin** [comment]
Look at first 3 designs

**Comment by nithyadurai87** [comment]
@gurulenin 
can you make the first logo of
https://user-images.githubusercontent.com/15311390/40237550-69144eee-5ace-11e8-8ef0-273e27de012c.png

as blue color?

**Comment by tshrinivasan** [comment]
@gurulenin please share the source for the above logo.
like to change few colors and try.

**Comment by gurulenin** [comment]
![rect224](https://user-images.githubusercontent.com/15311390/47089523-a56d2900-d23e-11e8-80cb-ff4cdd58882c.png)

**Comment by tshrinivasan** [comment]
இது அருமை.

இப்போதைக்கு இதையே பயன்படுத்தலாம்.

தேவையெனில் பிறகு மாற்றிக் கொள்ளலாம்.

மிக்க நன்றி

**Comment by gurulenin** [comment]
![letterpad](https://user-images.githubusercontent.com/15311390/47093738-714a3600-d247-11e8-8307-d657b5084044.png)

**Comment by gurulenin** [comment]
![letterpad2](https://user-images.githubusercontent.com/15311390/47093755-7ad39e00-d247-11e8-8ea2-23b4ac22bb1e.png)
