### ISSUE TITLE
வங்கி கணக்கு உருவாக்க வங்கி விவரங்கள் சேகரிக்கவும்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/Organization#6]

**Comment by gnuanwar** [comment]
ok

**Comment by tshrinivasan** [comment]
வங்கிக் கணக்கு விவரங்கள்

Kaniyam Foundation
Account Number : 606101010050279
Union Bank Of India
West Tambaram, Chennai
IFSC - UBIN0560618

**Comment by gnuanwar** [comment]
bank cheque books collected signing authority arnachalam signature taken in cheque book karkee is pending
